---
title: "Berrien Tables"
format: docx
execute:
  echo: false
  warning: false
  message: false
  error: false
editor_options: 
  chunk_output_type: console
---

```{r}
source("../scripts/getData.R")
source("../scripts/functions.R")
source("../scripts/subsetData.R")
source("../scripts/levels.R")
```


Which choice best describes the community’s perception of the local hospital’s services? 

```{r}
# create frequency table screening services for Berrien ----------------------------

berrien_screening_services_table <- 
  create_frequency_table(data, perception, perception_levels, "Berrien")

berrien_screening_services_table

```


Which statement best describes how many days each week that you engage in exercise for more than 30 minutes? 

```{r}

# create frequency table exercise for Berrien ----------------------------

berrien_exercise_table <- 
  create_frequency_table(data, exercise, exercise_levels, "Berrien")

berrien_exercise_table
```


Unable to access care? Why? 

```{r}

# create frequency table medical care unable why for Berrien ----------------------------

berrien_medical_care_unable_why_table <- 
  create_frequency_table(data, medcare_unable_y, medcare_unable_y_levels, "Berrien")

berrien_medical_care_unable_why_table 
```

Where do you go for care? 

```{r}


# create frequency table where care for Berrien ----------------------------

berrien_where_care_table <- 
  create_frequency_table(data, where_care, where_care_levels, "Berrien")

berrien_where_care_table

```


Outside?

```{r}

# create frequency table outside community for Berrien ----------------------------

berrien_outside_community_table <- 
  create_frequency_table(data, outside_comm, outside_comm_levels, "Berrien")

berrien_outside_community_table


```


Where outside?

```{r}


# create frequency table outside_comm_where for Berrien ----------------------------

berrien_outside_comm_where_table <- 
  create_frequency_table(data, outside_comm_where, outside_comm_where_levels, "Berrien")

berrien_outside_comm_where_table
```


Pcp?

```{r}

# create frequency table pcp for Berrien ----------------------------

berrien_pcp_table <- 
  create_frequency_table(data, pcp, pcp_levels, "Berrien")


berrien_pcp_table

```


Wait time?

```{r}


# create frequency table wait_time for Berrien ----------------------------

berrien_wait_time_table <- 
  create_frequency_table(data, wait_time, wait_time_levels, "Berrien")

berrien_wait_time_table

```


Specialist?

```{r}


# create frequency table specialist for Berrien ----------------------------

berrien_specialist_table <- 
  create_frequency_table(data, specialist, specialist_levels, "Berrien")

berrien_specialist_table

```


Telehealth?

```{r}
# create frequency table telehealth for Berrien ----------------------------

berrien_telehealth_table <- 
  create_frequency_table(data, telehealth, telehealth_levels, "Berrien")

berrien_telehealth_table

```


Satisfaction?

```{r}

# create frequency table satisfaction for Berrien ----------------------------

berrien_satisfaction_table <- 
  create_frequency_table(data, satisfaction, satisfaction_levels, "Berrien")

berrien_satisfaction_table

```


Insurance?

```{r}

# create frequency table insurance for Berrien ----------------------------

berrien_insurance_table <- 
  create_frequency_table(data, insurance, insurance_levels, "Berrien")

berrien_insurance_table

```   

